# video_only.yaml
# annotation 없이 비디오 경로만 지정. prompt에 따라 task 수행 (captioning, grounding 등)
# /media/user/img_backup1/Img_DB/2.VLM/tmp_vid/
mode: video_only

paths:
  video_list:
    # - Classification_DB/tmp_vid/snake_snitch_360.mp4
    # - Classification_DB/tmp_vid/Pool_cue_throwing.mp4
    # - Classification_DB/tmp_vid/pizza_fight/pizza_fight_1280_720.mp4
    # - Classification_DB/tmp_vid/pizza_fight/pizza_fight_960_540.mp4
    # - Classification_DB/tmp_vid/pizza_fight/pizza_fight_640_360.mp4
    # - Classification_DB/tmp_vid/pizza_fight/pizza_fight_320_180.mp4
    - Classification_DB/tmp_vid/pizza_fight_roi_crop.mp4
    # - Classification_DB/tmp_vid/bucket_fire.mp4
    # - Classification_DB/tmp_vid/bucket_fire_center_crop.mp4
    # - Classification_DB/tmp_vid/bucket_fire_leftop_crop.mp4
    # - Classification_DB/tmp_vid/auction_riot.mp4
    # - Classification_DB/tmp_vid/barbershop/barbershop_arson_fireself_1080.mp4
    # - Classification_DB/tmp_vid/barbershop/barbershop_arson_fireself_960.mp4
    # - Classification_DB/tmp_vid/barbershop/barbershop/arson_fireself_640.mp4
    # - Classification_DB/tmp_vid/barbershop/barbershop_arson_fireself_320.mp4
    # - Classification_DB/tmp_vid/seasoned_shrimp_resol/seasoned_shrimp_recipe_2560_1440.mp4
    # - Classification_DB/tmp_vid/seasoned_shrimp_resol/seasoned_shrimp_recipe_1920_1080.mp4
    # - Classification_DB/tmp_vid/seasoned_shrimp_resol/seasoned_shrimp_recipe_1280_720.mp4
    # - Classification_DB/tmp_vid/seasoned_shrimp_resol/seasoned_shrimp_recipe_854_480.mp4
    # - Classification_DB/tmp_vid/seasoned_shrimp_resol/seasoned_shrimp_recipe_640_360.mp4
    # - Classification_DB/tmp_vid/asdf_674_360.mp4